config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'landing_pages#landing_page'

  devise_for :admins, only: [:sessions]
  devise_for :vendors, only: [:sessions, :registrations], controllers: {
      sessions: "vendors/sessions",
      registrations: "vendors/registrations"
  }
  devise_scope :vendor do
    get 'vendors/sessions/resend_otp', as: 'vendor_resend_otp'
    post 'vendors/sessions/authenticate', as: 'vendor_authentication'
  end

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  authenticated :vendor do
    root 'vendors/dashboards#index'
    namespace 'vendors' do
      resources :dashboards, only: [:index]
      resources :locations, only: [:index, :new, :create, :edit, :update]
      resources :users, only: [:index]
      resources :deliveries, only: [:index]
    end
  end

  authenticated :admin do
    root 'dashboards#index'
    resources :dashboards, only: [:index]
    resources :product_categories, except: [:show, :destroy]
    resources :tickets, except: [:destroy, :new, :show]
    get 'subscription_request' => 'tickets#subscription_request'
    resources :products
    get 'cash_payments/all', to: 'cash_payments#all', as: 'all_cash_payments'
    resources :cash_payments, only: [:index, :update, :show]
    resources :payments, only: [:index, :show]
  end

  post 'user_token', to: 'api/v1/user_token#create', as: 'user_token_create'
  scope module: 'api' do
    namespace :v1 do
      namespace :users do
        resources :registrations, only: [:create]
        resource :profiles, only: [:update, :show]
        post 'registrations/validate_user', as: 'validate_user'
        get 'resend_otp', to: 'registrations#resend_otp', as: 'resend_otp'
        resources :locations, only: [:index, :create, :show, :update], defaults: {format: :json}
        resource :wallets, only: [:show], defaults: {format: :json}
        resources :transactions, only: [:show, :index], defaults: {format: :json}
        resources :products, only: [:index, :show], defaults: {format: :json}
        resources :subscription_items, only: [:index, :update], defaults: {format: :json}
        resources :subscriptions, only: [:create, :index, :destroy], defaults: {format: :json}
        resources :cash_payments, only: [:create]
        resources :passwords, only: [:create]
        resource :passwords, only: [:update]
      end
      resources :razor_pay_payments, only: [:create]
    end
  end

  get 'landing_page' => 'landing_pages#landing_page'
  get 'features' => 'landing_pages#features'
  get 'about' => 'landing_pages#about'
  get 'pricing' => 'landing_pages#pricing'
  post 'create_ticket' => 'landing_pages#create_ticket'
  get 'subscription_request' => 'landing_pages#new_subscription_request'
  post 'subscription_request' => 'landing_pages#create_subscription_request'

end

app/models/cash_payment.rb
class CashPayment < ApplicationRecord
  DUE_DAYS = 2

  belongs_to :user, inverse_of: :cash_payments
  belongs_to :payment, inverse_of: :cash_payment
  has_many :payment_tokens, through: :payment

  monetize :amount_in_paisa, as: 'amount'

  scope :unpaid, -> {where(paid: false)}

  scope :join_associates, ->(query = nil) do
    base_query = joins(:user, :payment)
                     .select("cash_payments.*, users.name as user_name")
    if query.present?
      base_query = base_query.where('lower(users.name) LIKE :text OR lower(users.email) LIKE :text OR lower(users.mobile) LIKE :text', text: "%#{query.downcase}%")
    end
    base_query
  end

  before_validation :set_due_date
  validates_presence_of :date, :due_date, :time_slot
  after_create_commit do
    CashPaymentRequestWorker.perform_at(2.days.from_now, self.id)
  end

  def paid!
    update(paid: true, paid_at: Time.zone.now)
    payment.update(status: 'Paid')
    payment.create_receipt
  end

  def self.create(user, time_slot, parent)
    amount_hash = parent.payment_entity.amount
    obj = CashPayment.transaction do
      payment = Payment.create(
          amount: amount_hash[:amount],
          total: amount_hash[:total],
          discount: amount_hash[:discount],
          wallet: amount_hash[:wallet],
          status: 'Payment To be Collected',
          user: user,
          paid_through: 'Cash',
          date: Time.zone.now
      )
      return payment if payment.errors.present?
      cash_payment = user.cash_payments.create(payment: payment, date: Date.today, time_slot: time_slot, amount: payment.amount)
      if cash_payment.errors.present?
        payment.delete
      end
      return cash_payment if cash_payment.errors.present?
      user.payment_tokens.where(token: amount_hash[:tokens]).each do |token|
        token.paid!(payment, 'Cash')
      end
      cash_payment
    end
    obj
  end

  private

  def set_due_date
    self.due_date = Date.today + DUE_DAYS.days
  end

end

app/controllers/api/v1/users/cash_payments_controller.rb
module Api::V1::Users
  class CashPaymentsController < UserApiController

    before_action :set_subscription

    def create
      if @parent.payment_entity.amount[:tokens].size.positive?
        obj = CashPayment.create(current_user, cash_payment_params[:time_slot], @parent)
        if obj.persisted?
          render json: {message: "Payment is successful"}, status: :created
        else
          render json: {errors: "Payment is not successful, #{obj.errors.full_messages.to_sentence}"}, status: :unprocessable_entity
        end
      end
    end

    private

    def cash_payment_params
      params.require(:cash_payment).permit(:id, :time_slot)
    end

    def set_subscription
      @parent = klass.find_by id: cash_payment_params[:id]
      return if @parent.present?
      render json: {errors: "#{klass.to_s} cannot be found"}, status: :unprocessable_entity
    end

    def klass
      params[:payment_to].present? ? params[:payment_to].constantize : Subscription
    end
  end
end

app/controllers/cash_payments_controller.rb
class CashPaymentsController < BaseAdminController

  before_action :set_cash_payment, only: [:show, :update]

  def index
    @cash_payments = CashPayment.unpaid.join_associates(params[:text]).order(:created_at)
  end

  def all
    @cash_payments = CashPayment.all.join_associates(params[:text]).order(:created_at)
  end

  def show

  end

  def update
    if params[:cash_payment][:confirm] == 'Freshgala'
      @cash_payment.paid!
      redirect_to cash_payments_path
    else
      render js: "alert('Type Freshgala')"
    end
  end

  private

  def set_cash_payment
    @cash_payment = CashPayment.find params[:id]
  end
end

app/views/cash_payments/_cash_payment_layout.html.erb
<div class="box" style="margin: 2rem auto">
  <div class="content">
    <div class="title-enc">
      <h4 class="break white left">
        <span>Cash Payments</span>
      </h4>
    </div>
  </div>

  <div class="tabs is-boxed is-centered">
    <ul>
      <% cash_payments_link.each do |link| %>
        <li class="<%= 'is-active' if link[:path] == request.path %>">
          <%= link_to link[:name], link[:path] %>
        </li>
      <% end %>
    </ul>
  </div>

  <%= yield %>
</div>

app/views/cash_payments/all.html.erb
<%= render 'cash_payment_layout' do %>
  <% if CashPayment.exists? %>
    <%= form_with url: all_cash_payments_path, data: {remote: false}, method: :get do |f| %>
      <div class="field has-addons">
        <div class="control">
          <button class="button is-static"><%= icon 'fas', 'search' %></button>
        </div>
        <div class="control is-expanded">
          <%= f.text_field :text, class: 'input', placeholder: 'Search by user name, email or mobile...', value: params[:text] %>
        </div>
        <div class="control">
          <%= f.submit 'Search', class: 'button is-info' %>
        </div>
      </div>
    <% end %>
    <div class="table-container">
      <table class="table is-striped is-fullwidth">
        <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th class="has-text-centered">Amount</th>
          <th>Due Date</th>
          <th>Time Slot</th>
          <th>Paid</th>
        </tr>
        </thead>
        <tbody>
        <% @cash_payments.each do |cash_payment| %>
          <tr>
            <td><%= cash_payment.user_name %></td>
            <td><%= ldt cash_payment.date %></td>
            <td class="has-text-centered"><%= humanized_money_with_symbol cash_payment.amount %></td>
            <td><%= ldt cash_payment.due_date %></td>
            <td><%= cash_payment.time_slot %></td>
            <td>
              <% if cash_payment.paid? %>
                <%= icon('fas', 'check-circle', class: 'has-text-success') %>
              <% else %>
                <%= icon('fas', 'times-circle', class: 'has-text-danger') %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p class="has-text-centered">There are no payments.</p>
  <% end %>
<% end %>

app/views/cash_payments/index.html.erb
<%= render 'cash_payment_layout' do %>
  <% if CashPayment.unpaid.exists? %>
    <%= form_with url: cash_payments_path, data: {remote: false}, method: :get do |f| %>
      <div class="field has-addons">
        <div class="control">
          <button class="button is-static"><%= icon 'fas', 'search' %></button>
        </div>
        <div class="control is-expanded">
          <%= f.text_field :text, class: 'input', placeholder: 'Search by user name, email or mobile...', value: params[:text] %>
        </div>
        <div class="control">
          <%= f.submit 'Search', class: 'button is-info' %>
        </div>
      </div>
    <% end %>
    <div class="table-container">
      <table class="table is-striped is-fullwidth">
        <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th class="has-text-centered">Amount</th>
          <th>Due Date</th>
          <th>Time Slot</th>
          <th style="width: 10%"></th>
        </tr>
        </thead>
        <tbody>
        <% @cash_payments.each do |cash_payment| %>
          <tr>
            <td><%= cash_payment.user_name %></td>
            <td><%= ldt cash_payment.date %></td>
            <td class="has-text-centered"><%= humanized_money_with_symbol cash_payment.amount %></td>
            <td><%= ldt cash_payment.due_date %></td>
            <td><%= cash_payment.time_slot %></td>
            <td>
              <%= link_to 'Pay', cash_payment_path(cash_payment), class: 'button is-success' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p class="has-text-centered">There are no pending payments to be collected.</p>
  <% end %>
<% end %>

app/views/cash_payments/show.html.erb
<div style="margin: 3rem auto;">
  <%= link_to cash_payments_path do %>
    <%= icon 'fas', 'arrow-left' %> back
  <% end %>
  <div class="box">
    <div class="notification is-warning">
      This process is non reversible. Kindly make sure everything is correct.
      <br>
      Type "Freshgala" in the below box and press "Pay" button
    </div>
    <table class="table is-fullwidth">
      <tbody>
      <tr>
        <th>Name</th>
        <td><%= @cash_payment.user.name %></td>
      </tr>
      <tr>
        <th>Mobile</th>
        <td><%= @cash_payment.user.mobile %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= @cash_payment.user.email %></td>
      </tr>
      <tr>
        <th>Amount</th>
        <td><%= humanized_money_with_symbol @cash_payment.payment.amount %></td>
      </tr>
      <tr>
        <th>Wallet</th>
        <td><%= humanized_money_with_symbol @cash_payment.payment.wallet %></td>
      </tr>
      <tr>
        <th>Discount</th>
        <td><%= humanized_money_with_symbol @cash_payment.payment.discount %></td>
      </tr>
      <tr>
        <th>Total</th>
        <td><%= humanized_money_with_symbol @cash_payment.payment.amount %></td>
      </tr>
      </tbody>
    </table>
    <%= form_with model: @cash_payment, method: :patch do |f| %>
      <div class="field has-addons">
        <div class="control is-fullwidth is-expanded">
          <%= f.text_field :confirm, class: 'input', placeholder: 'Type Freshgala in the text box' %>
        </div>
        <div class="control">
          <%= f.submit 'Pay', class: 'button is-danger' %>
        </div>
      </div>
    <% end %>
  </div>
</div>