config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'landing_pages#landing_page'

  devise_for :admins, only: [:sessions]
  devise_for :vendors, only: [:sessions, :registrations], controllers: {
      sessions: "vendors/sessions",
      registrations: "vendors/registrations"
  }
  devise_scope :vendor do
    get 'vendors/sessions/resend_otp', as: 'vendor_resend_otp'
    post 'vendors/sessions/authenticate', as: 'vendor_authentication'
  end

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  authenticated :vendor do
    root 'vendors/dashboards#index'
    namespace 'vendors' do
      resources :dashboards, only: [:index]
      resources :locations, only: [:index, :new, :create, :edit, :update]
      resources :users, only: [:index]
      resources :deliveries, only: [:index]
    end
  end

  authenticated :admin do
    root 'dashboards#index'
    resources :dashboards, only: [:index]
    resources :product_categories, except: [:show, :destroy]
    resources :tickets, except: [:destroy, :new, :show]
    get 'subscription_request' => 'tickets#subscription_request'
    resources :products
    get 'cash_payments/all', to: 'cash_payments#all', as: 'all_cash_payments'
    resources :cash_payments, only: [:index, :update, :show]
    resources :payments, only: [:index, :show]
  end

  post 'user_token', to: 'api/v1/user_token#create', as: 'user_token_create'
  scope module: 'api' do
    namespace :v1 do
      namespace :users do
        resources :registrations, only: [:create]
        resource :profiles, only: [:update, :show]
        post 'registrations/validate_user', as: 'validate_user'
        get 'resend_otp', to: 'registrations#resend_otp', as: 'resend_otp'
        resources :locations, only: [:index, :create, :show, :update], defaults: {format: :json}
        resource :wallets, only: [:show], defaults: {format: :json}
        resources :transactions, only: [:show, :index], defaults: {format: :json}
        resources :products, only: [:index, :show], defaults: {format: :json}
        resources :subscription_items, only: [:index, :update], defaults: {format: :json}
        resources :subscriptions, only: [:create, :index, :destroy], defaults: {format: :json}
        resources :cash_payments, only: [:create]
        resources :passwords, only: [:create]
        resource :passwords, only: [:update]
      end
      resources :razor_pay_payments, only: [:create]
    end
  end

  get 'landing_page' => 'landing_pages#landing_page'
  get 'features' => 'landing_pages#features'
  get 'about' => 'landing_pages#about'
  get 'pricing' => 'landing_pages#pricing'
  post 'create_ticket' => 'landing_pages#create_ticket'
  get 'subscription_request' => 'landing_pages#new_subscription_request'
  post 'subscription_request' => 'landing_pages#create_subscription_request'

end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController

  layout 'landing_page'

  def landing_page
    build_subscription_request
    @ticket = Ticket.new
  end

  def features

  end

  def about

  end

  def pricing
    
  end

  def create_ticket
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      flash[:success] = 'Your request has been placed. Our agent will contact you shortly!'
      redirect_to root_path
    else
      build_subscription_request
      flash[:danger] = 'Please check the errors.'
      render :landing_page
    end
  end

  def create_subscription_request
    @subscription_request = SubscriptionRequest.create(subscription_request_params)
  end

  private

  def build_subscription_request
    @subscription_request = SubscriptionRequest.new
  end

  def ticket_params
    params.require(:ticket).permit(:name, :email, :mobile, :locality).merge(status: 'waiting')
  end

  def subscription_request_params
    params.require(:subscription_request).permit(:name, :email, :mobile, :quantity, :product, :address)
  end
end

app/views/landing_pages/_question_section.html.erb
<section class="section fg-questions-section has-text-light">
  <div class="container has-text-centered">
    <h3 class="is-size-3 has-text-weight-bold has-text-light has-text-centered" style="margin-bottom: 2rem">Do you have any questions?</h3>
    <br>
    <a href="#" class="button is-info is-large ">Contact Us</a>
  </div>
</section>

app/views/landing_pages/_subscription_request_form.html.haml
= simple_form_for @subscription_request, url: subscription_request_path, remote: true do |f|
  = f.input :name
  = f.input :email
  = f.input :mobile
  = f.input :address
  = f.input :product, as: :select, collection: ['Cow Milk', 'Buffalo Milk ']
  = f.input :quantity, input_html: {step: 0.5}
  .modal-footer
    = f.submit 'Submit', class: 'btn btn-success'

app/views/landing_pages/_thank_you.html.haml
.alert.alert-success{:role => "alert"}
  %h4.alert-heading Thank You!
  %p Aww yeah, you successfully request has been successfully placed. Our representative will contact you shortly.
  

app/views/landing_pages/_ticket_form.html.erb
<div class="columns is-centered">
  <div class="column is-8-desktop is-12-mobile">
    <p class="has-text-light has-text-weight-bold">
      Please get in touch using the contact form below, or email us at
      <strong><a href="mailto:help@freshgala.com" style="color: #f5d9ac">help@freshgala.com</a></strong>
    </p>
    <br>
    <p class="has-text-light has-text-weight-bold">
      You can also call us on <strong><a href="tel:+91994945543" style="color: #f5d9ac">(+91) 994945543</a></strong>
    </p>
    <br>
    <%= form_with model: @ticket, url: create_ticket_path, html: {class: 'fg-ticket-form'} do |f| %>
      <div class="field">
        <label for="name" class="label">Name</label>
        <%= f.text_field :name, class: 'input', placeholder: 'Enter Name', required: true %>
      </div>
      <div class="field">
        <label for="name" class="label">Email</label>
        <%= f.text_field :email, class: 'input', placeholder: 'Enter Email', required: true %>
      </div>
      <div class="field">
        <label for="name" class="label">Mobile</label>
        <%= f.text_field :mobile, class: 'input', placeholder: 'Enter Mobile', required: true %>
      </div>
      <div class="field">
        <label for="name" class="label">Locality</label>
        <%= f.text_field :locality, class: 'input', placeholder: 'Enter Locality', required: true %>
      </div>
      <br>
      <div class="field has-text-centered">
        <button type="submit" class="button is-success is-rounded">Send Message</button>
      </div>
    <% end %>
  </div>
</div>

app/views/landing_pages/about.html.erb
<section class="fg-about-page section has-text-light">
  <div class="container">
    <div class="content">
      <h1>About Freshgala</h1>
      <p>Yet to be updated</p>
    </div>
  </div>
</section>
<%= render 'landing_pages/question_section' %>

app/views/landing_pages/create_subscription_request.js.erb
<% if @subscription_request.errors.any? %>
$('#subscription_request_modal_area').html('<%= j render "subscription_request_form" %>');
<% else %>
$('#subscription_request_modal_area').html('<%= j render "thank_you" %>');
<% end %>

app/views/landing_pages/features.html.erb
<section class="section fg-features-page has-text-centered">
  <div class="content">
    <h1 class=" has-text-light">Features yet to be added</h1>
  </div>
</section>
<%= render 'landing_pages/question_section' %>

app/views/landing_pages/landing_page.html.erb
<section class="hero is-medium fg-hero is-fullheight">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="columns is-vcentered">
        <div class="column is-half">
          <%= image_tag 'landing1/products_image.png', class: '', alt: 'Freshgala product' %>
        </div>
        <div class="column is-half">
          <h1 class="is-size-2 is-size-4-mobile has-text-light has-font-weight-bold">
            Brew, <span class="has-text-success" style="text-decoration: underline">DRINK</span> and say <br> Moooo...!
          </h1>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section fg-headline-features">
  <div class="container">
    <div class="columns feature is-vcentered has-text-centered">
      <div class="is-offset-1 column">
        <%= image_tag 'landing1/products_icon_1.png', class: '', alt: 'Freshgala feature 1' %>
      </div>
      <div class="column">
        <div class="content">
          <h3 class="has-text-danger is-uppercase">Complete health benefits</h3>
        </div>
        <p class="is-size-4 has-text-light has-text-left">
          Want your kids to prosper by gaining Vitamins, Calcium, Zinc and all other minerals without any contamination. FreshGala offers you the complete package of health benefits compressed in a single bottle of fresh milk.
        </p>
      </div>
      <div class="column is-1"></div>
    </div>
    <hr>
    <div class="columns feature is-vcentered has-text-centered">
      <div class="is-offset-1 column">
        <div class="content">
          <h3 class="has-text-danger is-uppercase">Free home delivery</h3>
        </div>
        <p class="is-size-4 has-text-light has-text-left">
          Busy with your daily chores. Stop worrying. We deliver you the freshest milk sealed in (mention how you clean the bottles) treated bottles to your home and the best part is we do not get charge you for the delivery.
        </p>
      </div>
      <div class="column">
        <%= image_tag 'landing1/products_icon_2.png', class: '', alt: 'Freshgala feature 1' %>
      </div>
      <div class="column is-1"></div>
    </div>
    <hr>
    <div class="columns feature is-vcentered has-text-centered">
      <div class="is-offset-1 column">
        <%= image_tag 'landing1/products_icon_3.png', class: '', alt: 'Freshgala feature 1' %>
      </div>
      <div class="column">
        <div class="content">
          <h3 class="has-text-danger is-uppercase">Zero additives</h3>
        </div>
        <p class="is-size-4 has-text-light has-text-left">
          With zero additives (not even water) we offer you the purest of pure because we too care about your family’s health and happiness.
        </p>
      </div>
      <div class="column is-1"></div>
    </div>
    <hr>
    <div class="columns feature is-vcentered has-text-centered">
      <div class="is-offset-1 column">
        <div class="content">
          <h3 class="has-text-danger is-uppercase">Rich flavour</h3>
        </div>
        <p class="is-size-4 has-text-light has-text-left">
          Tastes like real milk, because it is. The perfect mixture of aroma, flavour and rich creaminess makes this milk enjoyable by all the people of your family especially the kids.
        </p>
      </div>
      <div class="column">
        <%= image_tag 'landing1/products_icon_4.png', class: '', alt: 'Freshgala feature 1' %>
      </div>
      <div class="column is-1"></div>
    </div>
  </div>
</section>
<section class="section fg-contact-form">
  <div class="container">
    <h3 class="is-size-3 has-text-weight-bold has-text-light has-text-centered" style="margin-bottom: 2rem">Do you want try?</h3>
    <%= render 'landing_pages/ticket_form' %>
  </div>
</section>

app/views/landing_pages/pricing.html.erb
<section class="fg-pricing-page section has-text-light">
  <div class="container">

  </div>
</section>
<%= render 'landing_pages/question_section' %>