config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'landing_pages#landing_page'

  devise_for :admins, only: [:sessions]
  devise_for :vendors, only: [:sessions, :registrations], controllers: {
      sessions: "vendors/sessions",
      registrations: "vendors/registrations"
  }
  devise_scope :vendor do
    get 'vendors/sessions/resend_otp', as: 'vendor_resend_otp'
    post 'vendors/sessions/authenticate', as: 'vendor_authentication'
  end

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  else
    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  authenticated :vendor do
    root 'vendors/dashboards#index'
    namespace 'vendors' do
      resources :dashboards, only: [:index]
      resources :locations, only: [:index, :new, :create, :edit, :update]
      resources :users, only: [:index]
      resources :deliveries, only: [:index]
    end
  end

  authenticated :admin do
    root 'dashboards#index'
    resources :dashboards, only: [:index]
    resources :product_categories, except: [:show, :destroy]
    resources :tickets, except: [:destroy, :new, :show]
    get 'subscription_request' => 'tickets#subscription_request'
    resources :products
    get 'cash_payments/all', to: 'cash_payments#all', as: 'all_cash_payments'
    resources :cash_payments, only: [:index, :update, :show]
    resources :payments, only: [:index, :show]
  end

  post 'user_token', to: 'api/v1/user_token#create', as: 'user_token_create'
  scope module: 'api' do
    namespace :v1 do
      namespace :users do
        resources :registrations, only: [:create]
        resource :profiles, only: [:update, :show]
        post 'registrations/validate_user', as: 'validate_user'
        get 'resend_otp', to: 'registrations#resend_otp', as: 'resend_otp'
        resources :locations, only: [:index, :create, :show, :update], defaults: {format: :json}
        resource :wallets, only: [:show], defaults: {format: :json}
        resources :transactions, only: [:show, :index], defaults: {format: :json}
        resources :products, only: [:index, :show], defaults: {format: :json}
        resources :subscription_items, only: [:index, :update], defaults: {format: :json}
        resources :subscriptions, only: [:create, :index, :destroy], defaults: {format: :json}
        resources :cash_payments, only: [:create]
        resources :passwords, only: [:create]
        resource :passwords, only: [:update]
      end
      resources :razor_pay_payments, only: [:create]
    end
  end

  get 'landing_page' => 'landing_pages#landing_page'
  get 'features' => 'landing_pages#features'
  get 'about' => 'landing_pages#about'
  get 'pricing' => 'landing_pages#pricing'
  post 'create_ticket' => 'landing_pages#create_ticket'
  get 'subscription_request' => 'landing_pages#new_subscription_request'
  post 'subscription_request' => 'landing_pages#create_subscription_request'

end

app/models/payment.rb
class Payment < ApplicationRecord

  has_paper_trail

  belongs_to :user, inverse_of: :payments
  has_one :user_transaction, inverse_of: :payment
  has_many :payment_tokens, inverse_of: :payment
  has_one :cash_payment, inverse_of: :payment
  has_one :payment_receipt, inverse_of: :payment

  monetize :amount_in_paisa, as: 'amount'
  monetize :wallet_in_paisa, as: 'wallet'
  monetize :total_in_paisa, as: 'total'
  monetize :discount_in_paisa, as: 'discount'

  validates_presence_of :amount, :paid_through, :user_id, :status
  validates :source_id, uniqueness: {scope: :paid_through}, if: Proc.new {|a| a.paid_through != 'Cash'}

  def user_location
    payment_tokens.first.parent.user_location
  end

  def vendor
    payment_tokens.first.parent.vendor
  end

  def vendor_location
    payment_tokens.first.parent.vendor_location
  end

  def create_receipt
    return if payment_receipt.present?
    PaymentReceiptWorker.perform_async(self.id)
  end

end

app/models/payment/receipt.rb
class Payment::Receipt

  def initialize(payment)
    @payment = payment
  end

  def create
    PaymentReceipt.transaction do
      create_receipt
      create_items
    end
  end

  private

  def create_receipt
    @payment_receipt = @payment.create_payment_receipt(
        user: @payment.user,
        vendor: @payment.vendor,
        date: @payment.date,
        status: 'Paid',
        user_location_id: @payment.user_location.id,
        vendor_location_id: @payment.vendor_location.id,
        wallet: @payment.wallet,
        discount: @payment.discount,
        user_location_text: @payment.user_location.address_array,
        vendor_location_text: @payment.vendor_location.address_array,
        paid_through: @payment.paid_through
    )
  end

  def create_items
    @payment.payment_tokens.each do |payment_token|
      @payment_receipt.payment_receipt_items.create(
          parent_type: payment_token.parent_type,
          parent_id: payment_token.parent_id,
          quantity: payment_token.parent.dates.count,
          unit_of_measurement: payment_token.parent.unit_of_measurement,
          rate: payment_token.parent.product_price,
          amount: payment_token.parent.amount,
          description: payment_token.parent.description
      )
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < BaseAdminController
  before_action :set_payment, only: [:show]

  def index
    @payments = Payment.all.includes(:user)
  end

  def show
    @payment_receipt = @payment.payment_receipt
  end

  private

  def set_payment
    @payment = Payment.find_by(id: params[:id])
  end

end

app/views/payments/_receipt_layout.html.erb
<div>
  <div style="text-align: right;">
    <% if request.present? %>
      <%= image_tag 'logo.png', class: 'receipt-image' %>
    <% elsif defined?(image_tags) %>
      <%= image_tag(attachments['logo.png'].url, width: 200, class: 'receipt-image') %>
    <% else %>
      <%= wicked_pdf_image_tag 'logo.png', class: 'receipt-image' %>
    <% end %>
  </div>
  <p style="margin: 0.5rem 0;">Thanks for choosing Freshgala, <%= @payment_receipt.user.name %>! Here is your
    receipt:</p>
  <table>
    <tbody>
    <tr>
      <td style="width: 50%;">
        <p>Receipt No: <span class="bold-font"><%= @payment_receipt.receipt_number %></span></p>
        <p>Paid Date: <span class="bold-font"><%= ldt_with_time @payment_receipt.date %></span></p>
        <p>Paid Through: <span class="bold-font"><%= @payment_receipt.paid_through %></span></p>
      </td>
      <td style="width: 50%;">
        <p>Receipt To:</p>
        <p class="bold-font"><%= @payment_receipt.user.name %></p>
        <%= address_splitter(@payment_receipt.user_location_text) %>
      </td>
    </tr>
    </tbody>
  </table>
  <table>
    <tbody>
    <tr>
      <td style="width: 50%;">
        <p>Vendor:</p>
        <p class="bold-font"><%= @payment_receipt.vendor.name %></p>
        <%= address_splitter(@payment_receipt.vendor_location_text) %>
      </td>
      <td style="width: 50%;"></td>
    </tr>
    </tbody>
  </table>
  <div style="margin-top: 0.75rem">
    <table class="receipt-table">
      <thead>
      <tr>
        <td style="width: 65%">Description</td>
        <td style="width: 20%;text-align: center">Quantity</td>
        <td class="num" style="width: 15%;">Price</td>
      </tr>
      </thead>
      <tbody>
      <% @payment_receipt.payment_receipt_items.each do |payment_receipt_item| %>
        <tr>
          <td><%= payment_receipt_item.description %></td>
          <td style="text-align: center">
            <%= payment_receipt_item.quantity %><%= payment_receipt_item.unit_of_measurement %>
            x <%= currency_symbol %>&nbsp;<%= humanized_money payment_receipt_item.rate %>
          </td>
          <td class="num pct"><%= currency_symbol %>&nbsp;<%= humanized_money payment_receipt_item.amount %></td>
        </tr>
      <% end %>
      </tbody>
      <tfoot>
      <tr>
        <td></td>
        <td class="total-text">Item Total:</td>
        <td class="num pct"><%= currency_symbol %>&nbsp;<%= @payment_receipt.total %></td>
      </tr>
      <tr>
        <td></td>
        <td class="total-text">Wallet:</td>
        <td class="num pct"><%= currency_symbol %>&nbsp;<%= @payment_receipt.wallet %></td>
      </tr>
      <tr>
        <td></td>
        <td class="total-text">Discount:</td>
        <td class="num pct"><%= currency_symbol %>&nbsp;<%= @payment_receipt.discount %></td>
      </tr>
      <tr class="grand-total">
        <td></td>
        <td class="total-text">Grand Total:</td>
        <td class="num pct"><%= currency_symbol %>&nbsp;<%= @payment_receipt.grand_total %></td>
      </tr>
      </tfoot>
    </table>
  </div>
  <div style="margin-top: 2.5rem;">
    <div class="notification-box">
      <span class="bold-font">Note:</span> This is an acknowledgement of payment for your order. Invoice will be
      sent independently for each month. Thank you.
    </div>
  </div>
</div>

app/views/payments/index.html.erb
<div class="box" style="margin: 2rem auto">
  <div class="content">
    <div class="title-enc">
      <h4 class="break white left">
        <span>Payments</span>
      </h4>
    </div>
  </div>
  <div class="table-container">
    <table class="table is-fullwidth is-striped">
      <thead>
      <tr>
        <th>User</th>
        <th>Date</th>
        <th>Paid Through</th>
        <th class="has-text-right">Amount</th>
        <th class="has-text-centered">Actions</th>
      </tr>
      </thead>
      <% @payments.each do |payment| %>
        <tr>
          <td><%= payment.user.name %></td>
          <td><%= ldt payment.date %></td>
          <td><%= payment.paid_through %></td>
          <td class="has-text-right"><%= humanized_money_with_symbol payment.amount %></td>
          <td class="has-text-centered">
            <% if payment.payment_receipt.present? %>
              <%= link_to 'Show details', payment_path(payment), class: 'button is-small' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/payments/show.html.erb
<div style="margin: 2rem auto">
  <%= link_to payments_path do %>
    <%= icon 'fas', 'arrow-left' %> back
  <% end %>
  <div class="box">
    <%= render 'payments/receipt_layout' %>
  </div>
</div>